# Generated by Django 4.0.5 on 2022-07-09 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Id categoria')),
                ('NombreCategoria', models.CharField(max_length=35, verbose_name='Nombre Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.CharField(max_length=9999, primary_key=True, serialize=False, verbose_name='id producto')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre productos')),
                ('descripcion', models.TextField(max_length=300, verbose_name='Descripcion de producto')),
                ('precio', models.IntegerField(verbose_name='Precio producto')),
                ('imagen', models.ImageField(null=True, upload_to='Productos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
